#gg.jte.development-mode=true
#spring.application.name=students_web_api
server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/quanlysinhvien"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true